"""Add recommendation_id to Reward

Revision ID: 4d3d276863b7
Revises: 5bed5d2c8108
Create Date: 2026-07-19 03:25:10.122663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3d276863b7'
down_revision: Union[str, None] = '5bed5d2c8108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('recommendation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rewards', 'recommendations', ['recommendation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.drop_column('rewards', 'recommendation_id')
    # ### end Alembic commands ###
