"""make telemetry nullable

Revision ID: 5ee16159ef39
Revises: 7ff09692d09d
Create Date: 2026-07-20 23:22:04.039800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee16159ef39'
down_revision: Union[str, None] = '7ff09692d09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.alter_column('time_of_day',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('location_aqi',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('weather_temp',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.alter_column('weather_temp',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('location_aqi',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('time_of_day',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
