"""Add GamificationSetting

Revision ID: 7ff09692d09d
Revises: b3e781a86b26
Create Date: 2026-07-20 17:01:20.518696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff09692d09d'
down_revision: Union[str, None] = 'b3e781a86b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamification_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamification_settings')
    # ### end Alembic commands ###
