from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware

from app.routes import ai, community, emission, environment, simulation, user, auth, marketplace, admin

app = FastAPI(title="Carbon Guardian AI", version="1.0.0")
STATIC_DIR = Path(__file__).resolve().parent / "static"

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
def health() -> dict:
    """Return the health status of the API."""
    return {"status": "ok", "service": "Carbon Guardian AI"}


@app.get("/", include_in_schema=False)
def dashboard() -> FileResponse:
    """Serve the React frontend static dashboard."""
    return FileResponse(STATIC_DIR / "index.html")


app.include_router(auth.router)
app.include_router(user.router)
app.include_router(emission.router)
app.include_router(ai.router)
app.include_router(community.router)
app.include_router(simulation.router)
app.include_router(environment.router)
app.include_router(marketplace.router)
app.include_router(admin.router)

# Mount the static directory
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
# Mount the assets directory generated by Vite
app.mount("/assets", StaticFiles(directory=STATIC_DIR / "assets"), name="assets")
